# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Незаблокований користувач')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Адміністратор')),
            ],
            options={
                'verbose_name': 'Користувачі',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')])),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_coach', models.BooleanField(default=False)),
                ('club', models.ManyToManyField(to='auth_main.Club')),
            ],
        ),
    ]
