# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_main', '0004_auto_20180301_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/no-img.jpg', upload_to='avatars/'),
        ),
    ]
