# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_main', '0005_auto_20180302_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/no-img.png', upload_to='avatars/'),
        ),
    ]
