# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_main', '0009_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'user'), (2, 'manager')], default=1),
        ),
    ]
