# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 15:30
from __future__ import unicode_literals

import auth_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_main', '0011_auto_20180403_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verificated',
            field=models.BooleanField(default=False, verbose_name='Is user verificated'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default=auth_main.models.generate_email_hash, max_length=63, verbose_name='Verification code'),
        ),
    ]
