# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_main', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_group',
            field=models.CharField(default='', max_length=63, verbose_name='Age group'),
        ),
    ]
