# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Competition name')),
                ('count_days', models.SmallIntegerField(verbose_name='Count days')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(default='competitions/logos/no-img.png', upload_to='competitions/logos/', verbose_name='Logo')),
                ('region', models.CharField(choices=[('world', 'World'), ('europe', 'Europe'), ('ukraine', 'Ukraine')], max_length=100, verbose_name='Region')),
                ('track_count', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Count tracks')),
                ('is_creating_finished', models.BooleanField(default=False, verbose_name='Is creating finished')),
                ('started_at', models.DateField(verbose_name='Started at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is team registration completed')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is user registration completed')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Freestyle'), (2, 'Butterfly'), (3, 'Backstroke'), (4, 'Breaststroke'), (5, 'Dolphin kick')], verbose_name='Distance type')),
                ('length', models.SmallIntegerField(verbose_name='Distance length')),
                ('day', models.SmallIntegerField(verbose_name='Day number')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active invitation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelayRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Relay race length')),
                ('count_members', models.SmallIntegerField(verbose_name='Count members')),
                ('day', models.SmallIntegerField(verbose_name='Day number')),
                ('type', models.SmallIntegerField(choices=[(1, 'Mixed'), (2, 'Separated')], verbose_name='Distance type')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='RelayRaceTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Team for relay race')),
                ('result_time', models.IntegerField(default=0, verbose_name='Result time')),
                ('time', models.IntegerField(verbose_name='Time for distance')),
                ('relay_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelayRace')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Team name')),
                ('logo', models.ImageField(default='logos/no-img.png', upload_to='logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRelationToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coach', models.BooleanField(default=False, verbose_name='Is coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Time for distance')),
                ('result_time', models.IntegerField(default=0, verbose_name='Result time')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Distance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelayRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelayRaceTeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invitations',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='invitations',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
