# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdistance',
            name='result_time',
            field=models.CharField(default='', max_length=100, verbose_name='Result time'),
        ),
        migrations.AlterField(
            model_name='userdistance',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Time for distance'),
        ),
    ]
