# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='logos/no-img.png', upload_to='logos/'),
        ),
    ]
