# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180511_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistance',
            name='result_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Result time'),
        ),
        migrations.AddField(
            model_name='userdistance',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time for distance'),
        ),
    ]
