# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdistance_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_register_finished',
            field=models.BooleanField(default=False, verbose_name='Is register finished'),
        ),
        migrations.AlterField(
            model_name='userdistance',
            name='result_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Result time'),
        ),
    ]
