# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180520_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='pool_sizes',
            field=models.CharField(default='50,25', max_length=255, verbose_name='Pools sizes'),
        ),
    ]
