# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180319_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='region',
            field=models.CharField(choices=[('world', 'World'), ('europe', 'Europe'), ('ukraine', 'Ukraine')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
