# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_competition_pool_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistance',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count points'),
        ),
    ]
