# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_competition_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='users',
        ),
        migrations.AddField(
            model_name='competitionuser',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition'),
        ),
        migrations.AddField(
            model_name='competitionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition'),
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
