# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userdistance_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdistance',
            name='pre_time',
            field=models.IntegerField(default=0, verbose_name='Time for distance'),
        ),
    ]
