# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20180326_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_type', models.SmallIntegerField(choices=[(1, 'Freestyle'), (2, 'Butterfly'), (3, 'Backstroke'), (4, 'Breaststroke'), (5, 'Dolphin kick')])),
                ('length', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Distance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='track_count',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distance',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition'),
        ),
    ]
