# Generated by Django 2.0.4 on 2018-04-03 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180329_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(default='competitions/logos/no-img.png', upload_to='competitions/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Competition name'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='region',
            field=models.CharField(choices=[('world', 'World'), ('europe', 'Europe'), ('ukraine', 'Ukraine')], max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='started_at',
            field=models.DateField(verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='track_count',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Count tracks'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='competitionuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance_type',
            field=models.SmallIntegerField(choices=[(1, 'Freestyle'), (2, 'Butterfly'), (3, 'Backstroke'), (4, 'Breaststroke'), (5, 'Dolphin kick')], verbose_name='Distance type'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='length',
            field=models.SmallIntegerField(verbose_name='Distance length'),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active invitation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='logos/no-img.png', upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Team name'),
        ),
        migrations.AlterField(
            model_name='teamrelationtouser',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='Is coach'),
        ),
        migrations.AlterField(
            model_name='userdistance',
            name='time',
            field=models.TimeField(verbose_name='Time for distance'),
        ),
    ]
