# Generated by Django 2.0.4 on 2018-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180403_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdistance',
            name='time',
            field=models.IntegerField(verbose_name='Time for distance'),
        ),
    ]
