# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180501_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='distance_type',
            new_name='type',
        ),
    ]
