# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_competition_count_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_creating_finished',
            field=models.BooleanField(default=False, verbose_name='Is creating finished'),
        ),
    ]
