# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_distance_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionteam',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is team registration completed'),
        ),
        migrations.AddField(
            model_name='competitionuser',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is user registration completed'),
        ),
        migrations.AddField(
            model_name='userdistance',
            name='result_time',
            field=models.IntegerField(default=0, verbose_name='Result time'),
        ),
    ]
