# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20180507_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='Relay race length')),
                ('count_members', models.SmallIntegerField(verbose_name='Count members')),
                ('day', models.SmallIntegerField(verbose_name='Day number')),
                ('type', models.SmallIntegerField(choices=[(1, 'Mixed'), (2, 'Separated')], verbose_name='Distance type')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='RelayRaceTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Team for relay race')),
                ('result_time', models.IntegerField(default=0, verbose_name='Result time')),
                ('time', models.IntegerField(verbose_name='Time for distance')),
                ('relay_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelayRace')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelayRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RelayRaceTeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
