# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_size', models.CharField(max_length=50, verbose_name='Pool size')),
                ('distance_length', models.SmallIntegerField(verbose_name='Distance length')),
                ('distance_type', models.SmallIntegerField(choices=[(1, 'Freestyle'), (2, 'Butterfly'), (3, 'Backstroke'), (4, 'Breaststroke'), (5, 'Dolphin kick')], verbose_name='Distance type')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='Gender')),
            ],
        ),
    ]
