# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpoints',
            name='points',
            field=models.TextField(default='', verbose_name='Points'),
            preserve_default=False,
        ),
    ]
